plugins:
  - "@dotcom-tool-kit/webpack"
  - "@dotcom-tool-kit/component"
  - "@dotcom-tool-kit/jest"
  - "@dotcom-tool-kit/eslint"
hooks:
  test:local:
    - Eslint
    - JestLocal
  test:ci:
    - JestCI
  build:local:
    - WebpackDevelopment
options:
  '@dotcom-tool-kit/circleci':
    nodeVersion:
      - '22.12-browsers'
