plugins:
  - "@dotcom-tool-kit/webpack"
  - "@dotcom-tool-kit/component"
  - "@dotcom-tool-kit/jest"
  - "@dotcom-tool-kit/eslint"
commands:
  test:local:
    - Eslint
    - Jest
  test:ci:
    - Jest:
        ci: true
  build:local:
    - Webpack:
        envName: 'development'

options:
  plugins:
    '@dotcom-tool-kit/circleci':
      cimgNodeVersions: [22.12-browsers]